### ISSUE TITLE
Get-KbUpdate output is limited to 25 records 

### ISSUE THREAD

**Issue by nani1211** [potatoqualitee/kbupdate#101]
Get-KbUpdate is giving 25 patches for sql server 2017. but when i checked on https://www.catalog.update.microsoft.com/Home.aspx it it returning 28 results in 2 pages. I am thinking problem is with paging.

**Comment by potatoqualitee** [comment]
yeah, i will have to figure out how to do paging :/

**Comment by potatoqualitee** [comment]
this has been addressed in the latest release!

**Comment by potatoqualitee** [comment]
```
$results = Get-KbUpdate -Pattern "Windows Server 2019" -MaxPages 2 -Source Web
$results.Count | Should -Be 50
```
