### ISSUE TITLE
Save-KBUpdate architecture logic not working - using wrong character

### ISSUE THREAD

**Issue by MSIH** [potatoqualitee/kbupdate#103]
The links section are seperated by "-" not "_"
http://download.windowsupdate.com/d/msdownload/update/software/secu/2020/05/windows10.0-kb4552926-x86-ndp48_e136f0b75612a2444e4cecc91fa7a1f3d08593ab.msu
http://download.windowsupdate.com/d/msdownload/update/software/secu/2020/05/windows10.0-kb4552926-x64-ndp48_3aeb81a5f71e515f6eda4508e575d13d0a58305b.msu
http://download.windowsupdate.com/d/msdownload/update/software/secu/2020/05/windows10.0-kb4552926-x64-ndp48_3aeb81a5f71e515f6eda4508e575d13d0a58305b.msu

https://github.com/potatoqualitee/kbupdate/blob/11b1c2bac13ff334edd91dfc37c88bdce02432f5/public/Save-KbUpdate.ps1#L145                 

I think should be:
`   $templinks += $object.Link | Where-Object { $PSItem -match "$($arch)-" }`

and 
https://github.com/potatoqualitee/kbupdate/blob/11b1c2bac13ff334edd91dfc37c88bdce02432f5/public/Save-KbUpdate.ps1#L148

I think should be:
`$templinks += $object.Link | Where-Object { $PSItem -match "64-" }`

**Comment by potatoqualitee** [comment]
this appears to be fixed

```
Get-KbUpdate -Pattern kb4552926 | select Title, Architecture

Title                                                                                            Architecture
-----                                                                                            ------------
2020-05 Cumulative Update for .NET Framework 4.8 for Windows 10 Version 1607 (KB4552926)         x86
2020-05 Cumulative Update for .NET Framework 4.8 for Windows Server 2016 for x64 (KB4552926)     x64
2020-05 Cumulative Update for .NET Framework 4.8 for Windows 10 Version 1607 for x64 (KB4552926) x64
```

**Comment by potatoqualitee** [comment]
```
Save-KbUpdate -Pattern kb4552926 -Path C:\temp -Architecture x86


    Directory: C:\temp


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----         5/4/2020   6:47 AM       30573494   windows10.0-kb4552926-x86-ndp48_e136f0b75612a2444e4cecc91fa7a1f3d08593ab.msu
```
