### ISSUE TITLE
Working together wsusscn2.cab ?

### ISSUE THREAD

**Issue by lixaotec** [potatoqualitee/kbupdate#106]
Dear @potatoqualitee , 

First of all, congratulations for the great tool.

I was wondering if you have considered making your tool working together with wsusscn2.cab?

I see that wsusscn2.cab seem very updated, with a couple of days behind in fact, but using it as a source, we could track (using field SuperseedBy) KB until their latest and having a good way to automate the download of latest KB at once.

What do you think about? Is it feasable?

Best

**Comment by potatoqualitee** [comment]
That sounds really cool. Can you tell me more about the scenario? Is wsusscn2.cab something you'll have locally? How is it parsed?

**Comment by lixaotec** [comment]
wsusscn2.cab is officially distributed by MS: 
https://docs.microsoft.com/en-us/windows/win32/wua_sdk/using-wua-to-scan-for-updates-offline

It has to be downloaded and by using a simple PS script it does scan the system for the updates needed in this file (its a huge file, around 1 GB). But it works.

Maybe, if we use this mether as starting point, we could use your tool to track the most update packages for the ones resulting from wsusscn2.cab.

I dont think it will be a huge work, and perhaps it could be just a single PS script that does all.

Also we could do a task for download the CAB within days or months of interval, that will be enough.

Give a look at there please, youll notice that there is a simple way of achieving if we merge those solutions.

**Comment by potatoqualitee** [comment]
I've been looking for something like this! Thanks so much. Happy to explore.

**Comment by potatoqualitee** [comment]
just some notes for me 

```powershell
$UpdateSession = New-Object -ComObject Microsoft.Update.Session
$UpdateServiceManager = New-Object -ComObject Microsoft.Update.ServiceManager
$UpdateService = $UpdateServiceManager.AddScanPackageService("Offline Sync Service", "C:\Users\ctrlb\Downloads\wsusscn2.cab", 1)
$UpdateSearcher = $UpdateSession.CreateUpdateSearcher()

Write-Host "Searching for updates..."

$UpdateSearcher.ServerSelection = 3 #' ssOthers
$UpdateSearcher.ServiceID = $UpdateService.ServiceID
$SearchResult = $UpdateSearcher.Search("IsInstalled=0")
$Updates = $SearchResult.Updates

If ($Updates.Count -eq 0) {
    Write-Host "There are no applicable updates."
    break
}

Write-Host "List of applicable items on the machine when using wssuscan.cab:"

0..($Updates.Count - 1) | ForEach-Object {
    $update = $Updates.Item($psitem)
    Write-Host $update.Title
    Next
}
```

**Comment by potatoqualitee** [comment]
check for admin

**Comment by potatoqualitee** [comment]
btw, im streaming the development of support for this request and actually using it to keep the module updated on a monthly basis, so if you want to follow https://twitch.tv/potatoqualitee, you may be able to see some of it in action 🚀

**Comment by lixaotec** [comment]
hey there, where did it reach by now? perhaps I may try helping.

**Comment by lixaotec** [comment]
Was trying to figure out how -Latest option works, when -Source Web is set. Could you explain?
Should It 'loop' through get kbs coming from SupersededBy?

**Comment by potatoqualitee** [comment]
no idea by now, that is some black magic :( but im still interested in parsing that cab

**Comment by potatoqualitee** [comment]
the monthly database update  in [kbupdate-library](https://www.powershellgallery.com/packages/kbupdate-library/) is now powered by wsusscn2.cab. 

You can also download wsusscn2.cab using `Save-KbScanFile`
