### ISSUE TITLE
Get-kbupdates returns unreliable results

### ISSUE THREAD

**Issue by hvoges** [potatoqualitee/kbupdate#110]
Hi Chrissy, 
I stumbled upon your module today and love it. Thank you for your community-work. 
I have an issue with Get-KBUpdates. I tried to find the lastest CU for Windows Server 2019 and used the following Command:

get-kbupdate -OperatingSystem 'Windows Server 2019' -Latest -Architecture x64 -Pattern "Cumulative Update for Windows"

I get different results each time. First I got a quite lengthy list including different versions of Windows Server (2016,...). Finally I got a "2020-11 Cumulative Update Preview for Windows Server 2019 for x64-based Systems (KB4586839)", what I initially tried to prevent by using the Pattern "Cumulative Update for Windows". Somehow the Filter doesn´t seem to work as expected. Here another example:

get-kbupdate -Latest -Pattern "Cumulative Update for Windows Server 2019" | select Title

Title
-----
2019-10 Cumulative Update for Windows Server 2016 (1803) for x64-based Systems (KB4519978)
2019-12 Cumulative Update for .NET Framework 4.8 for Windows Server 2016 for x64 (KB4532997)
2020-11 Cumulative Update Preview for Windows Server 2019 for x64-based Systems (KB4586839)
2019-12 Cumulative Update for Windows Server, version 1903 for x64-based Systems (KB4530684)
2019-12 Cumulative Update for .NET Framework 4.8 for Windows Server 2016 (1803) for x64 (KB4533000)
2019-10 Cumulative Update for .NET Framework 4.8 for Windows Server 2016 (1803) for x64 (KB4519572)
2019-12 Cumulative Update for Windows Server, version 1909 for x64-based Systems (KB4530684)

**Comment by lixaotec** [comment]
get-kbupdate -Latest -Pattern "Cumulative Update for Windows Server 2019" -OperatingSystem "Windows Server 2019" | select Title

?

**Comment by hvoges** [comment]
The Title-Part is the colum-Header, below is the column-content. I would expect to get only updates with "Cumulative Update for Windows Server 2019" in the title, but instead I receive a bunch of Cumulative Updates for different Products.

**Comment by lixaotec** [comment]
im just getting the latest 

![image](https://user-images.githubusercontent.com/40803484/108361790-b2650300-71d1-11eb-9636-73074a7ebad0.png)

**Comment by hvoges** [comment]
Jupp, you are right - it works if you also use the Operating-System-Filter, but that always returns a preview-update as latest. To get the latest RTM-CU, I left out the Operating-System and tried to filter only for the Pattern. But then the filter seems to filter every single keyword and not the whole string.

**Comment by lixaotec** [comment]
yeah, im junt learning the thing.

Just noticed weird info regarding a package KB4535101

If we use this too , it says it has no SupersededBy , but in microsoft catalog it is outdated

https://www.catalog.update.microsoft.com/ScopedViewInline.aspx?updateid=023374c4-d3ea-4691-a5af-85db115710ad

**Comment by lixaotec** [comment]
-Source web seems to works

**Comment by potatoqualitee** [comment]
Thanks so much for the report! This shouldddd be fixed in today's release: 1.5.7
