### ISSUE TITLE
[Save-KbUpdate] When piping, please do not use OperatingSystem or Product filters.

### ISSUE THREAD

**Issue by ninjachamp** [potatoqualitee/kbupdate#111]
When I try to use the OperatingSystem or Product parameters I get warning below but I'm not piping anywhere.

`Save-KbUpdate -kb 4535680 -OperatingSystem 'Windows Server 2016'`
`WARNING: [00:47:51][Save-KbUpdate] When piping, please do not use OperatingSystem or Product filters. It's assumed that you` `are piping the results that you wish to download, so unexpected results may occur.`

This kb is valid for several products but how do I download for just 2016?

**Comment by Mananix** [comment]
For me its working with this.

Get-KbUpdate -Architecture x64 -Name $name -OperatingSystem 'Windows 8.1' | Save-KbUpdate 

But yes it woul be nice if the save-KbUpdate cmdlet would do it. otherwise i dont know why it should have the parmeters :)

THX to the developer of this module.

**Comment by ninjachamp** [comment]
> For me its working with this.
> 
> Get-KbUpdate -Architecture x64 -Name $name -OperatingSystem 'Windows 8.1' | Save-KbUpdate
> 
> But yes it would be nice if the save-KbUpdate cmdlet do it. otherwise i dont know why it should have the parmeters :)
> 
> THX to the developer of this module.

Thank you @Mananix that worked for me!
