### ISSUE TITLE
You can only specify one KB when using FilePath

### ISSUE THREAD

**Issue by dhs-rec** [potatoqualitee/kbupdate#112]
I get above message, even when providing exactly one pattern, for example:
```
PS D:\updates> Save-KbUpdate -Pattern KB2553313 -Architecture x86 -FilePath KB2553313.cab
WARNING: [09:01:34][Save-KbUpdate] You can only specify one KB when using FilePath
```
I guess it comes from [this check](https://github.com/potatoqualitee/kbupdate/blob/0b40e1418be35dae61a7b4ffa7c7a97109935a78/public/Save-KbUpdate.ps1#L106), which should be `-gt 1`, not `-gt 0`.

**Comment by potatoqualitee** [comment]
good catch! thank you. this will be fixed in an upcoming release.
