### ISSUE TITLE
Review Get-SuperInfo Function

### ISSUE THREAD

**Issue by lixaotec** [potatoqualitee/kbupdate#113]
Dear @potatoqualitee 

I was taking a look at the Get-SuperInfo function, and I wish you have a look at there in order to review it.

I think it is broken for some cases (KB4570332 for example)

$Text should references $Text.Content for applying regex

Also I´m trying to figure out the logic for this switch (it seems not working very well)

 switch -Wildcard ($span.Value) {
        "*div style*" { $regex = '">\s*(.*?)\s*<\/div>' }
        "*a href*" { $regex = "<div[\s\S]*?'>(.*?)<\/a" }
        default { $regex = '">\s*(.*?)\s*<\/div>' }
    }

Thank you in advance

**Comment by potatoqualitee** [comment]
Thank you! This has been fixed. Sorry for the delay and thanks for using the module.
