### ISSUE TITLE
Last Modification Date - should be in filename

### ISSUE THREAD

**Issue by lixaotec** [potatoqualitee/kbupdate#115]
Dear

I suggest that Last Modification Date (a date from catalog) should be applied to the filename when downloading (perhaps like a preference) to sort KBs for instalation, (note that KD id order number not always has precedence)

suggs:
2021-02-16 - windows10.0-kb4601383-x64_0161100ba8b1413a84cbd26b514b00c299bac8a4.msu
2021-02-08 - windows10.0-kb4601393-x64_010c229fddd5d60a8a41d2e5bb95308671196b03.msu

as you may see here (https://support.microsoft.com/en-us/topic/february-16-2021-kb4601383-os-build-17763-1790-preview-9535653c-8012-47f0-0f90-44cdd57cdc36) kb4601393 updates windows update, and kb4601383 cannot be installed before

**Comment by wonghoi** [comment]
You can sort the results returned by `Get-KbUpdate` with `Sort-Object`. Here's an example:
```
Get-KbUpdate  ... | Sort-Object -Property -LastModified
```
If you are manually installing them from Explorer, you can select 'Detailed' view and 'Date modified' is a column that you can sort your files with. 
![image](https://user-images.githubusercontent.com/33778214/160233599-ea03d7a5-b4df-414f-8244-89d96b0176d0.png)

Making the filename longer (when there are other alternatives) isn't a good idea as we can easily run out of characters if it's in a deeply nested path.

**Comment by potatoqualitee** [comment]
i agree @wonghoi  -- in addition, filenames can't be change due to integration with other systems that rely on a specific filename format.
