### ISSUE TITLE
install kbupdate in offline server

### ISSUE THREAD

**Issue by TCP-88** [potatoqualitee/kbupdate#116]
how can i install kbupdate in offline server with only 1 online server.

**Comment by potatoqualitee** [comment]
You would use `Save-Module kbupdate -Path C:\temp\` then copy the resulting folders to your PowerShell path on the remote server.

The module path is any one of the module directories found when you execute:

`$env:psmodulepath`

**Comment by potatoqualitee** [comment]
You can now find the module in the PowerShell Gallery or here on GH. It's v1.5
