### ISSUE TITLE
Issues with Install-KBUpdate when run locally with RMM as SYSTEM user

### ISSUE THREAD

**Issue by DanPhoaser** [potatoqualitee/kbupdate#118]
Btw, Amazing module, thank you!
Unable to install kbupdate, getting errors about the remote access issue and enabling wmi remote management. 

If this is run locally it should not attempt creating a remote session for invoking and instead run the commands locally. I don't have the exact log output this second but once I get it I will provide here.

Also, by using $env:home as the download path for saving in files, it will not find the correct path when run as SYSTEM user. I had to force set-variable for that to a valid local path to save the kb files successfully.

**Comment by potatoqualitee** [comment]
Thanks for the report, Dan!

> If this is run locally it should not attempt creating a remote session for invoking and instead run the commands locally. 

It doesn't under normal circumstances -- the integration tests for the module run successfully against local. I think what happens is that the environment you're running it under, I did not expect or accommodate for. It compared env: which probably doesn't exist when running as SYSTEM. I'll get that fixed today.

Also huge thanks for the note about $env:! I'll fix that too.

**Comment by potatoqualitee** [comment]
this has been fixed in a recent release 👍🏼
