### ISSUE TITLE
Sort on CIM incorrect - causing no updates to be shown

### ISSUE THREAD

**Issue by DanPhoaser** [potatoqualitee/kbupdate#120]
https://github.com/potatoqualitee/kbupdate/blob/0b40e1418be35dae61a7b4ffa7c7a97109935a78/public/Get-KbInstalledUpdate.ps1#L198

No updates are shown from your CIM search due to the Sort-Object logic used. 

**Recommend to change to below:**
`$allcim = Get-CimInstance -ClassName Win32_QuickFixEngineering | Sort-Object HotFixID -Unique`

**Comment by potatoqualitee** [comment]
oh, yuck. thank you for finding that. your suggestion will be added to an upcoming release.
