### ISSUE TITLE
OpeartingSystem switch not filtering out operating system

### ISSUE THREAD

**Issue by wonghoi** [potatoqualitee/kbupdate#125]
Here's an example where the OperatingSystem switch does not do anything
`Get-KbUpdate -Name 2479943 -Language English -Architecture x64 -OperatingSystem 'Windows 7' | Out-GridView -Passthru`
![image](https://user-images.githubusercontent.com/33778214/160061933-1b310790-3776-401d-84f1-94b3fd6b78f4.png)

I searched for code that contains the string OperatingSystem and  it seems like the OperatingSystem was just adding a string to the search box instead of filtering by SupportedProducts field. 
![image](https://user-images.githubusercontent.com/33778214/160062141-4638f661-2c84-4843-98e8-e2583dc2552d.png)

Searching 'Windows 7' in the catalog will return [Embedded updates](https://answers.microsoft.com/en-us/windows/forum/all/search-filter-string-httpcatalogupdatemicrosoftcom/a85604ca-917f-4ede-bf28-055d58411202) as well. There's also [no exclusion operator](https://answers.microsoft.com/en-us/windows/forum/all/where-can-i-find-all-of-the-search-syntax-that-is/68ce0e47-7cd1-4ac4-96b3-f70e5debeb32) in search string either.

**Comment by wonghoi** [comment]
I wrote a simple patch fix wrapper script (say `Get-KbUpdate_os.ps1`) that captures the `-OperatingSystem` parameter and use it to filter by `SupportedProducts` property of the returned objects:

```
param([string]$OperatingSystem)
$hits = Get-KbUpdate @args
if( $PSBoundParameters.ContainsKey('OperatingSystem') )
{
	$hits = $hits | Where-Object -Property SupportedProducts -eq $OperatingSystem
}
return $hits

```
The above code could probably be fixed by adding
`$results = $results | Where-Object -Property SupportedProducts -eq $OperatingSystem
`
right after
`$results = Invoke-TlsWebRequest -Uri $url`

Let me check the Github etiquettes and test the fix first before submitting it.

**Comment by potatoqualitee** [comment]
Thank you for the issue, @wonghoi! The reason I put the OperatingSystem in the Query String is because Microsoft's SupportedProjects isn't as standardized as I hoped. I did expect that people would use SupportedProducts in the way that you are doing it. I imagine that The word Windows showed up in the description along with the number 7, and that's why you're getting wild variations in SupportedProducts.

There won't be a perfect solution but perhaps doing SupportedProducts -match will do better. or perhaps even a like. In your case, 'Windows 7' will not match that Windows Embedded Standard 7, which you probably didn't want anyway, but there are other examples that are non-standard that you'd still want, like perhaps you want `Windows XP` but that shows up as `Windows Xp x64 Edition`. So ultimately, this is a bit of a bummer due to the lack of standardization.

Perhaps what would work is an index of all the different ways they say a product, then making that match a more boarder product with a dictionary, know what I mean?

**Comment by potatoqualitee** [comment]
The problem with the last solution is that it's gongoing, especially with each wierdly named release of Windows 10, and I was hoping to set and forget this project (tho I do need to revisit)

**Comment by wonghoi** [comment]
Now I see why. The code was searching for matching `SupportedProducts` OR `Title` so it was matching `'Windows.*7'` in the title because all OS's title start with 'Windows' and the KB number contains a '7'.
![image](https://user-images.githubusercontent.com/33778214/160210838-fb5eddac-d051-409a-813b-17793935209d.png)

I also noticed the code in the `$Product` branch is a copy of `$OperatingSystem` branch with the said variable names switched. Wouldn't it mean `-Product` switch is effectively identical to `-OperatingSystem` switch?

I think regex on `Title` field is hopelessly unreliable. Missing a few updates (because Microsoft mal-formatted their database or their entries contains typos or inconsistencies) that are later prompted by Windows Update is better than getting a ton of false matches because it's free-style entry that do not follow predictable rules like other fields does. 

Just throwing it out there (might not be a good idea): would it be easier to separate the logic of 'filtering by regex-ing `Title` field' from the rest (filter by intended database fields) and have the user optionally turn on the `-includeTitleMatches` switch if they wish to expand the search results based on parsing the `Title` field?

In my use case, I'm using this to crawl all the relevant updates for a slipstream, so it'd always be one architecture, one os, one language and the latest kb superseding the older ones. I was using wsusoffline.net but I think it does not account for the precedence rules and it missed some kb that I was prompted by Windows Update later, so I collected the new KB numbers (and merge it with the slipstreamed kb numbers in the first pass) and hope your kbupdate module will sort out the precedence for me. So the tool will be useless to me if I cannot filter out the irrelevant files because it's having false positives from regex-ing the `Title` field.

**Comment by wonghoi** [comment]
I did a little bit of homework on Powershell and came up with an algorithm to do the `$Architecture` and `$OperatingSystem` filtering in `Search-Kb.ps1`:

```
if($Architecture) 
{
	# AMD64 is another way of saying x64 in multi-architecture strings
	if ("x64" -in $Architecture) { $Architecture += "AMD64"	}		
	# Include wildcards
	$Architecture += ("All", $nul)		
	
	# Algorithm
	# =========
	#   1) build a list of possible unique arch strings
	$unique_arch_strings = $allobjects.Architecture | Select-Object -Unique
	#   2) filter the unique arch strings with relevance to the list of arch requested		
	#   2a) Multi-Architecture are joined by '_' delimiters
	#   2b) each unique arch string get broken into N tokens and each 1 token is checked for membership in $Architecture
	#   2c) ".Where(cond).Count -gt 0" is a way to express "any(cond)"
	$unique_arch_strings = $unique_arch_strings.Where({ $_.Split('_').Where({$_ -in ($Architecture)}).Count -gt 0 })
	#   3) keep only records that matches the filtered unique arch strings
	$allObjects = $allObjects | Where-Object {$_.Architecture -in $unique_arch_strings}
}

# Suggestion: -Product can quietly merge with -OperatingSystem
$OperatingSystem += $Product

if($OperatingSystem)
{
	# There's one quirk that Micosoft might have set multiple-entries for 
	# dual use updates for "Windows 2003" and "Windows 2003 R2" yet
	# the type display gets collected as strings.
	$dual_use_Win2k3 = 'System.Collections.ArrayList';
	if( ($OperatingSystem -match 'Windows 2003').Count -gt 0 )
	{
		$OperatingSystem += $dual_use_Win2k3
	}
	
	# After the conversion above, these are exact matches, so 
	# we don't need a unique choice qualification process like in Architecture
	$allObjects = $allObjects | Where-Object {$_.SupportedProducts -in $OperatingSystem}						
}
```
I still haven't spent the time to fully understand the logic you are using to repair malformed WSUS objects that doesn't have an `Id` field (which typically misses a bunch of other fields such as `SupportedPlatforms` yet `Architecture` and `Language` are still available). 

Seems like it's handling the `Architecture` and `SupportedProducts` reliably as long as the fields are not empty.
![image](https://user-images.githubusercontent.com/33778214/160232263-69d2059d-5c59-4041-af46-21e00e0ce27d.png)
Whether we detect or enter these missing fields from `Title` field for the blank/mal-formatted WSUS objects is the project for another day, as it'd require dumping all updates Microsoft offers so far for analysis and come up with a robust regex pattern for it :)

**Comment by potatoqualitee** [comment]
this will be useful thank you

**Comment by potatoqualitee** [comment]
fixed in recent release, thanks again for the report!
