### ISSUE TITLE
Windows 2003 showed up as System.Collections.ArrayList in SupportedProducts

### ISSUE THREAD

**Issue by wonghoi** [potatoqualitee/kbupdate#126]
I noticed Windows 2003 was crawled as
```
SupportedProducts : System.Collections.ArrayList
```
![image](https://user-images.githubusercontent.com/33778214/160215991-6a7c1c01-384c-44de-b71d-7d6301065c28.png)

Is it possible that the update applied to multiple products and the array was accidentally converted to string (with the stdout text) without reading displaying the contents of the array? Is it possible to get the actual array or join the strings using a comma/semi-colon separated list?

**Comment by potatoqualitee** [comment]
mmm, which would be better -- an array or just a `Select-Object -First 1`? if we make it an array, it'll mess up a match that we use later on (i think)

**Comment by wonghoi** [comment]
I found some KBs such as 4507004 that you must have a list of multiple items instead of picking the first one or the last one:
![image](https://user-images.githubusercontent.com/33778214/160299619-1e755805-ac7b-4da9-9ede-d5dd50e2cd04.png)

Your regex for $supportedproducts for some reason parsed only the last item of the returned HTML
![image](https://user-images.githubusercontent.com/33778214/160299662-19c26294-f87a-48e4-8f07-733bbc2e6dec.png)
which turned out to be "Windows Embedded Standard 7", which means if I filter by "Windows 7", this item won't show up.

So this never got active for the KB:
![image](https://user-images.githubusercontent.com/33778214/160299776-f5169029-3813-4c49-a408-a9b4bb4b4569.png)

I noticed that `SupportedProducts` field never had multiple items separated by delimiters and I thought I should expect only 1 platform per update-id until I looked into the code. 

4507004 exclusively uses `Get-KbItemFromWeb` while 2393802 uses `Get-KbItemFromDb` (it tried `Get-KbItemFromWeb` too but no `$downloaddialogs` returned). So it looks like the current kbupdate did not flatten arrays into comma separated strings in DB method while the web method's array flattening routine never got used because the regex only retrieved the last item ignoring everything.

I think the matching logic of `$OpearingSystem` and `$Products` branch using it is broken already (any '7' in the KB number already breaks "Windows 7"). We might be better off with exact lookups since you already maintained a list of OS that can be recalled through tabs in `kbupdate.psm`)

**Comment by potatoqualitee** [comment]
I ended up handjamming it. This solved the issue and will soon be in a PR 👍🏼 

```
function Get-Info ($Text, $Pattern) {
    if ($Pattern -match "labelTitle") {
        if ($Pattern -match "SupportedProducts") {
            # no idea what the regex below does but it's not working for SupportedProducts
            # do it the manual way instead
            $block = [regex]::Match($Text, $Pattern + '[\s\S]*?\s*(.*?)\s*<\/div>').Groups[0].Value
            $supported = $block -split "</span>" | Select-Object -Last 1
            $supported.Trim().Replace("</div>","").Split(",").Trim()
        } else {
            # this should work... not accounting for multiple divs however?
            [regex]::Match($Text, $Pattern + '[\s\S]*?\s*(.*?)\s*<\/div>').Groups[1].Value
        }
    } elseif ($Pattern -match "span ") {
        [regex]::Match($Text, $Pattern + '(.*?)<\/span>').Groups[1].Value
    } else {
        [regex]::Match($Text, $Pattern + "\s?'?(.*?)'?;").Groups[1].Value
    }
}
```

**Comment by potatoqualitee** [comment]
Re. The arraylist, unfortunately, i didnt flatten them when importing, so 3000 records are arrays :(

**Comment by potatoqualitee** [comment]
fixed the whole db, this will be fixed in the upcoming release

**Comment by potatoqualitee** [comment]
this is resolved
