### ISSUE TITLE
Keep only the last modified file within search results

### ISSUE THREAD

**Issue by wonghoi** [potatoqualitee/kbupdate#127]
`-Latest` switch is 'latest KB following precedence rules', but Get-KbUpdate also return old versions of the exact same one KB update Id for the same OS, Architecture, Language that are useless. Hope there's a new feature such as `-KeepOnlyLastModified` for slipstreaming applications.

For now, I am just piping the results with this:
```
Get-KbUpdate_os ... | Sort-Object -Property @{Expression = "Id"; Descending = $true}, @{Expression = "LastModified"; Descending = $true} -Unique
```
The first field to sort is the grouping term/field which the first one from the sorted table that shares the same KB will be kept.

**Comment by potatoqualitee** [comment]
Thank you @wonghoi -- can you give me an example of a KB that does this?

**Comment by potatoqualitee** [comment]
Also thanks for showing me how to sort on two objects! I'd've probably done two sorts.

**Comment by wonghoi** [comment]
> Thank you @wonghoi -- can you give me an example of a KB that does this?

I'll have to look it up again since it has been a few weeks. I'm currently swamped with a few orders (in my business). Will try to get back to you after a week.

**Comment by potatoqualitee** [comment]
fortunately, i had an integration test with a matching failure 👍🏼  Thanks, this will be fixed in the next release

```
$results = Get-KbUpdate -Pattern 2416447, 979906 -Latest
```
