### ISSUE TITLE
Integration tests failed

### ISSUE THREAD

**Issue by wonghoi** [potatoqualitee/kbupdate#129]
I tried to submit a pull request but appveyor threw a bunch of errors. Then I looked into running the integration tests from on the unmodified package and it still failed. Can you take a look into it to make sure the `MASTER` branch passes the configured tests?

For example
![image](https://user-images.githubusercontent.com/33778214/161415764-caeada3c-5ebe-4c69-98ef-a0e9a67df3f0.png)

`tests\Integration test.ps1`
![image](https://user-images.githubusercontent.com/33778214/161415782-8a9f20bc-a3ad-4534-bb74-34aa5c9911fa.png)

Searching the entire code base for `results no longer exist`, it only appeared in `Get-KbUpdate.ps1`
![image](https://user-images.githubusercontent.com/33778214/161415822-14d52ab6-5072-4276-962e-364c2d180cfe.png)

So I typed [this](https://support.microsoft.com/app/content/api/content/help/en-us/4482972) in my browser and it showed:
![image](https://user-images.githubusercontent.com/33778214/161415872-82241469-0579-4d1b-92e3-ddda7b8078b0.png)

Looks like Microsoft got rid of the service (I tried other KB numbers as well) so this test is no longer valid.

I don't know if it's OK if I just fix the code, but I'm not sure if I am allowed to change the tests on my side.

**Comment by potatoqualitee** [comment]
yeah, looks like you can remove the test and also the secondary attempt :( i couldn't find any other microsoft site that provided the same functionality :/

**Comment by choebear** [comment]
I've been searching around for others having a problem accessing [https://www.catalog.update.microsoft.com/DownloadDialog.aspx](https://www.catalog.update.microsoft.com/DownloadDialog.aspx) without luck. [This appears to all be related to a recent change MSFT enacted two days ago. ](https://www.ghacks.net/2022/04/02/microsoft-update-catalog-downloads-are-now-using-https/) If anyone has a replacement or fix please let us know!

**Comment by wonghoi** [comment]
> I've been searching around for others having a problem accessing https://www.catalog.update.microsoft.com/DownloadDialog.aspx without luck. [This appears to all be related to a recent change MSFT enacted two days ago. ](https://www.ghacks.net/2022/04/02/microsoft-update-catalog-downloads-are-now-using-https/) If anyone has a replacement or fix please let us know!

For the mean time, you can just add a `.*` in the regex before `download.windowsupdate.com` to accept `*.download.windowsupdate.com`. Namely changing this line in `\public\Get-KbUpdate.ps1` to:
```
$links = $downloaddialog | Select-String -AllMatches -Pattern "(http[s]?\://.*download\.windowsupdate\.com\/[^\'\""]*)" | Select-Object -Unique
```
![image](https://user-images.githubusercontent.com/33778214/161647359-f5120d00-3d4b-4109-97e6-448ce0f335d1.png)

I submitted a pull request but a bunch of integration tests were broken. The tests also caught KB 4057113's SupersededBy/Supersedes field was not scrapped because because Microsoft removed the `TABINDEX` attribute. There's also some deep pains ahead as I see that this field has nested `<div>` blocks which regex is not designed to handle (it requires some sort of stack mechanism). 
![image](https://user-images.githubusercontent.com/33778214/161647812-2fce117e-18ea-4601-8938-393d7a2c71ab.png)
I'm thinking of using replacing the regex mechanism with a proper DOM/XPath parser. Microsoft removed deep tag extraction from `Invoke-WebRequest` which is under `Invoke-TlsWebRequest` that came with `kbupdate`, so I looked into other powershell-native solutions but they either involve IE or COM (HTMLfile) so it won't be portable. I tried casting the page into [xml] (technically it should be OK since xhtml is a form of xml) but Microsoft's implementation chokes on whitespaces in attributes and also the javascripts. I'm looking into Python's BeautifulSoup which parses the page correctly, but I have to worry about bundling a minimal Python to make kbupdate self-contained. It's going to be a bigger project than I thought. I'm still agonizing whether I should write a quick and snippet extractor to match `<div ...` and `</div>' at the proper nested levels (so it won't ended up crawling only the first item) or redesign the whole thing with a proper DOM parser that works for all fields.

**Comment by potatoqualitee** [comment]
so much has changed 😭  the new url im using is `https://support.microsoft.com/en-us/topic/$kb` which at least confirms that it used to be in the catalog. That URL seems to have a download link in it tho, so I'll explore getting what I can get from it.
