### ISSUE TITLE
Get-KbUpdate needs to be updated for new catalog download urls

### ISSUE THREAD

**Issue by wasserja** [potatoqualitee/kbupdate#130]
https://github.com/potatoqualitee/kbupdate/blob/8ebddbd4d0db6368a299f124ca14fcad987e4549/public/Get-KbUpdate.ps1#L419

Needs to be changed to 
$links = $downloaddialog | Select-String -AllMatches -Pattern "(http[s]?\://catalog\.s\.download\.windowsupdate\.com\/[^\'\""]*)" | Select-Object -Unique

**Comment by jessiewestlake** [comment]
> https://github.com/potatoqualitee/kbupdate/blob/8ebddbd4d0db6368a299f124ca14fcad987e4549/public/Get-KbUpdate.ps1#L419
> 
> Needs to be changed to $links = $downloaddialog | Select-String -AllMatches -Pattern "(http[s]?://catalog.s.download.windowsupdate.com/[^\'\""]*)" | Select-Object -Unique

Thank you! I'm also noticing that there are only a few properties returned now. I'm hoping it's just a matter of changing property names used in the friendly naming code.

**Comment by wcs-bjogus** [comment]
Matching both old and new.

`Select-String -AllMatches -Pattern "(http[s]?\://download\.windowsupdate\.com\/[^\'\""]*)|(http[s]?\://.*\.*\.download\.*\.windowsupdate\.com\/[^\'\""]*)"`

**Comment by potatoqualitee** [comment]
This has been fixed and published to the PowerShell Gallery (and here on GH), thanks for the report!
