### ISSUE TITLE
Search the updates for Windows Server 2012 but returns Windows Server 2012 and 2012 R2

### ISSUE THREAD

**Issue by legionliu** [potatoqualitee/kbupdate#140]
Get-KbUpdate will return both Windows 2012 and 2012 R2 updates when trying to search for Windows 2012. I have updated the script locally to fix the issue by searching the update with exactly wanted OS. For your reference:
Add '`"' for $OperatingSystem to Get-KbUpdate.ps1 line 232:

 $url = "https://www.catalog.update.microsoft.com/Search.aspx?q=$kb+`"$OperatingSystem`""
![image](https://user-images.githubusercontent.com/32904539/170253850-2d2e5317-397c-44b5-a1ff-25037324fd9d.png)

**Comment by potatoqualitee** [comment]
So I got this to work for Database but I'm not so sure the quotes work for the web

![image](https://user-images.githubusercontent.com/8278033/182331588-d4604a58-c37d-4212-8ed7-a67306a244e8.png)
