### ISSUE TITLE
get-kbupdate is not populating architecture for some KBs

### ISSUE THREAD

**Issue by chipwadeTM** [potatoqualitee/kbupdate#143]
Has anyone else run into this one and know of a fix?

=2019 SSUs=
PS> Get-kbupdate -Name KB5005112 -Simple

Title        : 2021-08 Servicing Stack Update for Windows 10 Version 1809 for x64-based Systems (KB5005112)
**Architecture :** 
Language     : 
UpdateId     : 2aa60267-ea74-4beb-9da4-bcb3da165726
Link         : https://catalog.s.download.windowsupdate.com/d/msdownload/update/software/secu/2021/08/windows10.0-kb5005112-x64_81d09dc6978520e1a6d44b3b15567667f83eba2c.msu

Title        : 2021-08 Servicing Stack Update for Windows 10 Version 1809 for x86-based Systems (KB5005112)
**Architecture :** 
Language     : 
UpdateId     : 68a3ced4-d2df-4e53-8f09-e679fd07f68c
Link         : https://catalog.s.download.windowsupdate.com/c/msdownload/update/software/secu/2021/08/windows10.0-kb5005112-x86_9c52dee3181a27bdc2a3f7dbbc8391c081c6871d.msu

Title        : 2021-08 Servicing Stack Update for Windows Server 2019 for x64-based Systems (KB5005112)
**Architecture :** 
Language     : 
UpdateId     : c93b3ce0-c637-47c6-9ba7-ca7725eb5a98
Link         : https://catalog.s.download.windowsupdate.com/d/msdownload/update/software/secu/2021/08/windows10.0-kb5005112-x64_81d09dc6978520e1a6d44b3b15567667f83eba2c.msu

Title        : 2021-08 Servicing Stack Update for Windows 10 Version 1809 for ARM64-based Systems (KB5005112)
**Architecture :** 
Language     : 
UpdateId     : d50c806b-462a-49fe-af2a-671fade8261a
Link         : https://catalog.s.download.windowsupdate.com/c/msdownload/update/software/secu/2021/08/windows10.0-kb5005112-arm64_cb652d860e52650db02d49802ac23eb481339019.msu

**Comment by potatoqualitee** [comment]
thanks, can confirm. ill check when i get a moment.

**Comment by crzsotona** [comment]
Get-kbupdate -Name KB5005112+x64
