### ISSUE TITLE
Install-KbUpdate

### ISSUE THREAD

**Issue by potatoqualitee** [potatoqualitee/kbupdate#17]

**Comment by potatoqualitee** [comment]
Gonna try to do this via DSC which is available on Windows 2012. Will explore this: https://github.com/PowerShell/xWindowsUpdate

As someone messaged me that i dont yet understand

> there’s a DSC resource, if you can use Invoke-DSCResource if you want to specify accounts to run it as and not use a MOF file, or putting together a generic MOF file, copying that everywhere, execute in system context and remove is also easy.

**Comment by koglerk** [comment]
@potatoqualitee If you're looking for a great intro level DSC tutorial, [Jess Pomfret uploaded one to Youtube last week](https://www.youtube.com/watch?v=N4E0fHG8RhE).

**Comment by potatoqualitee** [comment]
So happy to report that @jpomfret is actually working on the command as we speak 🤩!

She finally helped me understand DSC so I reached out and asked if she'd be interested. She said yes and already has a prototype 🚀

**Comment by maczamora** [comment]
`function Get-GuidsFromWeb ($kb) {
            Write-PSFMessage -Level Verbose -Message "$kb"
            Write-Progress -Activity "Searching catalog for $kb" -Id 1 -Status "Contacting catalog.update.microsoft.com"
            $results = Invoke-TlsWebRequest -Uri "https://www.catalog.update.microsoft.com/Search.aspx?q=$kb"
            Write-Progress -Activity "Searching catalog for $kb" -Id 1 -Completed

            $kbids = $results.InputFields |
            Where-Object { $_.type -eq 'Button' -and $_.Value -eq 'Download' } |
            Select-Object -ExpandProperty  ID

            if (-not $kbids) {
                try {
                    $null = Invoke-TlsWebRequest -Uri "https://support.microsoft.com/app/content/api/content/help/en-us/$kb"
                    Stop-PSFFunction -EnableException:$EnableException -Message "Matches were found for $kb, but the results no longer exist in the catalog"
                    return
                } catch {
                    Stop-PSFFunction -EnableException:$EnableException -Message "No results found for $kb"
                    return
                }
            }`

Is this looking for the kb udpate from the microsoft update catalog??

**Comment by potatoqualitee** [comment]
@maczamora please open a new issue - this is specifically for install

**Comment by maczamora** [comment]
@potatoqualitee sounds good. I'll open an issue. I'm not really having any problems with this, just have some questions on how you are able to get to the download box in the powershell script.

**Comment by potatoqualitee** [comment]
Heck yes, done-a-rama
