### ISSUE TITLE
What exactly is the use of a ScanFile

### ISSUE THREAD

**Issue by steviecoaster** [potatoqualitee/kbupdate#192]
What does this file contain? How is it useful to me in combination with `Install-KbUpdate`. Can we get a short blurb somewhere in the README or Wiki about this file and how to use it successfully?

**Comment by potatoqualitee** [comment]
Yes indeed! Will add more detailed docs 👍🏼

**Comment by potatoqualitee** [comment]
Please check out the changes I made here and let me know if you'd like additional info

https://github.com/potatoqualitee/kbupdate/commit/48b2f460cecfa983271d42a9552c86e5fd8b1a1f
