### ISSUE TITLE
Problem trying to use scanfile

### ISSUE THREAD

**Issue by Gilles92** [potatoqualitee/kbupdate#197]
Hello on an offline machine i try to use this command:
Get-KbNeededUpdate -ComputerName server01 -ScanFilePath $scanfile
But i have this error:
Exception from HRESULT: 0x8024402C
    + CategoryInfo          : OperationStopped: (:) [], COMException
    + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException
    + PSComputerName        : localhost

The command is working on an online machine.
Regards

**Comment by potatoqualitee** [comment]
Thanks for the report! Was able to repro and got a solution

**Comment by Gilles92** [comment]
Thank you !
