### ISSUE TITLE
Feature Update Enablement Package - Support

### ISSUE THREAD

**Issue by ramzcode** [potatoqualitee/kbupdate#199]
Hi,

Thank you and all the contributors for such a wonderful work.

I would like to know something that i am not sure about exactly, i.e. is it possible to install Feature updates ? These are not available on Catalog site. I don't see any doc either.

Please share some ideas on the feasibility. 

Also can a web server be used as the package repository ? 

Thanks in advance.

**Comment by potatoqualitee** [comment]
Hey Ramz,
Glad youre enjoying it! 

It might be possible if the application supports silent installs and you know the argument list. Check out this for more info:

https://github.com/potatoqualitee/kbupdate#can-i-install-other-applications-using-install-kbupdate

As for the web server being used as the package repo, the module supports WSUS. Outside of that, you could do some external PowerShell work to modify the download URL, download it and go from there.
