### ISSUE TITLE
Is it supposed to find On-Demand Hotifxes

### ISSUE THREAD

**Issue by gbargsley** [potatoqualitee/kbupdate#2]
I have tried a couple different hotfix numbers and I get 
`WARNING: No results found for 4483666`

Tried for SQL 2017
4506633
4483666

SQL 2016
4508636
4482972

**Comment by sysgoblin** [comment]
These are discoverable via the MS support API, however some of the download links no longer work or result in 404. May be due to their removal from the catalog for some reason...

https://support.microsoft.com/app/content/api/content/help/en-gb/$kbnumber

**Comment by potatoqualitee** [comment]
That is interesting. I had the same issue and wonder how we can handle it. Perhaps instead of "No results found for" .. we try to find it on the API, then say "We found it but it is no longer listed"
