### ISSUE TITLE
Last two days updates are not showing

### ISSUE THREAD

**Issue by ramzcode** [potatoqualitee/kbupdate#200]
Trying to run get-kbupdate for last 8 days but only shows from Oct-11, last two dates updates are not shown. Trying on macOS BTW.

Get-KbUpdate  -Since (Get-Date).AddDays(-8)  -Source Web

Below one returns yesterdays, i.e. 19-Oct ones.
get-kbupdate -Latest -Pattern "Dynamic Update for Windows 10" -Source Web| select Title    ##Using since last 8 days again returns nothing too.

Below one does't return anything 
get-kbupdate -Latest -Since (Get-Date).AddDays(-10)  -Source Web -Architecture x64 | select Title

Bit confusing, please advice

**Comment by potatoqualitee** [comment]
hey @ramzcode -- if you do a -Verbose, you'll see that Since is limited to the database lookups and it will set the source to database. I suppose I can make that a Stop-Function instead of a verbose that informs you. There's no way for me to search the web catalog using a Since that I know of.

**Comment by ramzcode** [comment]
@potatoqualitee  Noted thanks a lot, BTW can i update the database to be up to date with the catalog site ??

**Comment by potatoqualitee** [comment]
kbudpate's database is updated once a month on Patch Tuesday when they update their catalog/database. Anything after patch tuesday will have to come from the web :/
