### ISSUE TITLE
Specify KB by Office Product

### ISSUE THREAD

**Issue by Cowbeau** [potatoqualitee/kbupdate#207]
Hello! I was wondering, using this tool, is there a way to specify the KB by Microsoft Product, such as a KB that has an option for Server 2008 R2 or Windows 7, etc? Is there a parameter that allows for that level of specification?

Thanks!

**Comment by potatoqualitee** [comment]
You found the answer, @Cowbeau ? (I dont recall off the top of my head. Microsoft's catalog is messy and not standardized but I tried my best)

**Comment by Cowbeau** [comment]
I did! It was using the first type selectors in Powershell. Thank you!
