### ISSUE TITLE
Replicating functionality of PSWindowsUpdate `Get-WindowsUpdate -MicrosoftUpdate`

### ISSUE THREAD

**Issue by branpurn** [potatoqualitee/kbupdate#208]
Is there a way to point, say, `Install-KbUpdate`'s `-AllNeeded` parameter to Microsoft Update instead of WSUS or a cache file, similar to how this is implemented in PSWindowsUpdate?

This might look like the following,

`Install-KbUpdate -ComputerName localhost, sqlcs, sql01 -AllNeeded -MicrosoftUpdate`

**Comment by potatoqualitee** [comment]
Yes if you don't specify anything it will check Microsoft update eh? or do you use WSUS and want to sometimes bypass it?

**Comment by branpurn** [comment]
Correct-- a built-in way to bypass WSUS without changing configuration

**Comment by potatoqualitee** [comment]
k got itt thank you, that is possible

**Comment by codaamok** [comment]
This PR should add support this: https://github.com/potatoqualitee/kbupdate/pull/217

**Comment by potatoqualitee** [comment]
thanks, friend 🙇🏼
