### ISSUE TITLE
Suggestion: Prevent internal functions from being exported

### ISSUE THREAD

**Issue by sysgoblin** [potatoqualitee/kbupdate#21]
After module import internal functions are usable such as invoke-tlswebrequest.

To make this "private", you can remove the '-' from the functions within the private folder (e.g. Invoke-TLSWebRequest > InvokeTLSWebRequest) and amend the psm1 file to something like below:

```
$Public = @( Get-ChildItem -Path $PSScriptRoot\Public\*.ps1 -ErrorAction SilentlyContinue )
$Private = @( Get-ChildItem -Path $PSScriptRoot\Private\*.ps1 -ErrorAction SilentlyContinue )

Foreach ($import in @($Public + $Private)) {
    Try {
        . $import.fullname
    } Catch {
        Write-Error -Message "Failed to import function $($import.fullname): $_"

    }
}

Export-ModuleMember -Function *-* -Alias *
```

This will prevent these functions being exported but still allow internal use.

**Comment by potatoqualitee** [comment]
🤔 are you importing via the psd1 or on linux? it shows properly on windows

![image](https://user-images.githubusercontent.com/8278033/61054345-8e372280-a3ef-11e9-9880-e0bf6c8beced.png)

If it's otherwise on Linux, I'll update

**Comment by sysgoblin** [comment]
Tbh I generally import via psm1 so that explains it. 👍

**Comment by potatoqualitee** [comment]
ahh yes, i consider that developer mode. it's how i do it too.
