### ISSUE TITLE
KB5021657 almost 25 days old Update not available on Local DB

### ISSUE THREAD

**Issue by ramzcode** [potatoqualitee/kbupdate#210]
Thank you for this wonderful work!!

There are no document about the use of local DB. 

How can we force it to update with catalog site ?
Does the local DB cache when used with web based search?
What is the real need of localDB

Unable to fetch an update from Nov 2022. 

I am using the module on brew based pwsh environment. 

kindly clarify

**Comment by ramzcode** [comment]
![image](https://user-images.githubusercontent.com/76745955/207438393-35beb0d1-2b36-41a5-916d-c302561cda38.png)

**Comment by codaamok** [comment]
Microsoft maintain the offline scan file, this isn't something Chrissie maintains or updates. 

It's also fairly common for Microsoft to not put some updates in the offline scan file, and only offer them via WSUS/Windows Update.

**Comment by potatoqualitee** [comment]
Thank you, coda! I've been behind on the kb repo bc I changed jobs and am no longer using it :/
