### ISSUE TITLE
Does it fetch information from the internet, or from a local WSUS server?

### ISSUE THREAD

**Issue by Stephanevg** [potatoqualitee/kbupdate#3]
Woop, in the title :)
And would it be possible to make it fetch the detailed infos from a WSUS?

**Comment by potatoqualitee** [comment]
Currently, it only fetches from www.catalog.update.microsoft.com. I am unsure about making it fetch from WSUS. For my use-case, I cannot use WSUS so it's unlikely I'll explore the option. There are a lot of WSUS modules in the Gallery, however, so the code my be easily available to adapt.

**Comment by potatoqualitee** [comment]
If it turns out that WSUS is searchable and anyone would like to add the functionality, the parameter `SearchType` (or something) could be added that defaults to the catalog, but could also search WSUS.

**Comment by sysgoblin** [comment]
> Woop, in the title :)
> And would it be possible to make it fetch the detailed infos from a WSUS?

Is the use case for this along the lines of you're unable to query out to the internet, or you want to get detailed information on say all needed/approved patches listed in WSUS?

**Comment by potatoqualitee** [comment]
Good ol Boe!

https://learn-powershell.net/2013/07/07/use-the-wsus-api-and-powershell-to-query-the-susdb-database/

can allow the user to specify the server or they'll have to rely on the dll

`Add-Type -Path "$Env:ProgramFiles\Update Services\Api\Microsoft.UpdateServices.Administration.dll"` 

MSFT's take:
https://support.microsoft.com/en-us/help/4490414/windows-server-update-services-best-practices

> This is just a code example to get you started with PowerShell and the WSUS API. See links following for even more PowerShell scripts. This can be executed where the WSUS Administration Console is installed.

```
[void][reflection.assembly]::LoadWithPartialName("Microsoft.UpdateServices.Administration")
$WSUSServer = 'WSUS'
# This is your WSUS Server Name
$Port = 8530
# This is 8531 when SSL is enabled
$UseSSL = $False
#This is $True when SSL is enabled
Try {
    $Wsus = 	[Microsoft.UpdateServices.Administration.AdminProxy]::GetUpdateServer(`
	$WSUSServer,$UseSSL,$Port)
} Catch {
    Write-Warning "$($WSUSServer)<$($Port)>: $($_)"
    Break
}
```

WSUS API

**Comment by potatoqualitee** [comment]
bruhh
https://andys-tech.blog/2019/07/wsus-synchronization-fails-with-soapexception-after-july-8th-2019/


$config.MUUrl
$config.RedirectorChangeNumber


$server = Get-WsusServer
$config = $server.GetConfiguration()
# Check current settings before you change them 
$config.MUUrl
$config.RedirectorChangeNumber
https://sws.update.microsoft.com

**Comment by potatoqualitee** [comment]
Koof that API is slow. Gonna use it to get info about the SQL Server, then

```

SELECT distinct u.UpdateID, max(r.RevisionNumber) as revision, F.MUURL
FROM         dbo.tbUpdate u INNER JOIN
             dbo.tbRevision r ON u.LocalUpdateID = r.LocalUpdateID INNER JOIN
             dbo.tbFileForRevision FFR ON FFR.RevisionID= r.RevisionID INNER JOIN
             dbo.tbFile F ON FFR.FileDigest = F.FileDigest
group by UpdateID, MUURL



SELECT TOP (1000) [UpdateId]
      ,[RevisionNumber]
      ,[DefaultTitle]
      ,[DefaultDescription]
      ,[ClassificationId]
      ,[ArrivalDate]
      ,[CreationDate]
      ,[IsDeclined]
      ,[IsWsusInfrastructureUpdate]
      ,[MsrcSeverity]
      ,[PublicationState]
      ,[UpdateType]
      ,[UpdateSource]
      ,[KnowledgebaseArticle]
      ,[SecurityBulletin]
      ,[InstallationCanRequestUserInput]
      ,[InstallationRequiresNetworkConnectivity]
      ,[InstallationImpact]
      ,[InstallationRebootBehavior]
  FROM [SUSDB].[PUBLIC_VIEWS].[vUpdate]
```

**Comment by potatoqualitee** [comment]
@Stephanevg - can you check the `wsus` branch?

`Get-KbUpdate -Pattern 4011080 -WsusComputerName localhost`

unsure about the variable names but that's a working concept. should auto detect what it needs.

**Comment by potatoqualitee** [comment]
I think instead of WsusServer, I'm going to change it to Source Wsus and then require a Connect that either connects via SQL or Boe's PoshWSUS

**Comment by potatoqualitee** [comment]
nm, dont try for now - just committed some massive changes and it's not ready yet

**Comment by potatoqualitee** [comment]
K - this has been added to the module. You can now use `[string[]]$Source` which can be `Web`, `Database` or `Wsus`. To use the `Wsus` command, you must use `Connect-KbWsusServer` which is a wrapper for @proxb's PoshWSUS. PoshWSUS is now a required module.

**Comment by potatoqualitee** [comment]
```powershell
Connect-KbWsusServer -ComputerName server1 -SecureConnection
Get-KbUpdate -Pattern KB2764916 -Source Wsus
````
