### ISSUE TITLE
Search-KbUpdate

### ISSUE THREAD

**Issue by potatoqualitee** [potatoqualitee/kbupdate#5]
it's not reliable to search for x86, etc so to find the architecture for files, we'd need to search a few things

search filename, search description maybe? search the architecture field.

Offer -OperatingSystem -Architecture

**Comment by sysgoblin** [comment]
more than happy to help with more regex expressions for parsing these elements if you need any. ✌

**Comment by potatoqualitee** [comment]
haha! thank you, i will let you know for sure! still working out how i'll approach this. it's challenging.

**Comment by potatoqualitee** [comment]
make this internal, add -Latest to Get/Set which does the supersedes thing

**Comment by potatoqualitee** [comment]
-rt- in filename means not x64

**Comment by potatoqualitee** [comment]
need to add tests for diff archs and oses

**Comment by potatoqualitee** [comment]
Offer Language
