### ISSUE TITLE
Tagging the releases

### ISSUE THREAD

**Issue by jschpp** [potatoqualitee/kbupdate#51]
Hi. Love this module :-)

Would you mind tagging the releases? Then I'd get a notification if a new one is out.

**Comment by potatoqualitee** [comment]
glad you like it, great things are coming soon! i dont use releases myself but can add it to my build script, perhaps. can you provide the git commands that i can add to my script?

**Comment by jschpp** [comment]
I'm not sure where in your build process you'd put this. You would at least need an option to tell when to create an release an when not.

There is a Module by @rjmholt which is referenced [here](https://github.com/microsoft/PowerShellForGitHub/issues/110) which can automatically create github releases via `Publish-GitHubRelease`

The module itself is pretty much self explanatory.
If you want I can create a short script which will use this module to create the release tags. I'm just not sure when to run it.

**Comment by potatoqualitee** [comment]
oh that's speaking my language, thank you! i'll add it in though I don't have an ETA currently

**Comment by wsmelton** [comment]
An easier method would be to just use GitHub Action. This seems to be the best one to use as it will pick up your changelog entries if you use them:
https://github.com/marketplace/actions/git-release

If you just want a basic release: https://github.com/marketplace/actions/github-release

**Comment by rjmholt** [comment]
> There is a Module by @rjmholt which is referenced here which can automatically create github releases via Publish-GitHubRelease

Hmm, I should try and get that into https://github.com/microsoft/PowerShellForGitHub

**Comment by potatoqualitee** [comment]
thank you! i am now tagging the releases on gh
