### ISSUE TITLE
Fetch missing Windows updates

### ISSUE THREAD

**Issue by potatoqualitee** [potatoqualitee/kbupdate#59]
https://twitter.com/wincmdfu/status/1140668272821460995

````
#Powershell script to fetch missing #Windows updates

PS C:\> (New-Object -ComObject microsoft.update.session).CreateUpdateSearcher().Search("IsHidden=0 and IsInstalled=0").Updates | select Title,RebootRequired,CVEIds,IsMandatory

````

**Comment by potatoqualitee** [comment]
but do what with the information? I'm not sure

**Comment by potatoqualitee** [comment]
i did a comparison and it's not matching up

![image](https://user-images.githubusercontent.com/8278033/73654652-8f31e900-468c-11ea-9562-7e71b7eea1c2.png)

![image](https://user-images.githubusercontent.com/8278033/73654673-9eb13200-468c-11ea-9ad8-c015f883bd35.png)

so why are they considered missing?

**Comment by lixaotec** [comment]
not every missing is stated with an KB... so how to look for it, like "Dell Monitor"

**Comment by potatoqualitee** [comment]
All done in `Get-KbNeededUpdate`
