### ISSUE TITLE
The term 'Invoke-SqliteQuery' is not recognized

### ISSUE THREAD

**Issue by codaamok** [potatoqualitee/kbupdate#60]
Hello!

I love what you've made, it's brilliantly simple and so helpful! Thank you!

Simply running `Get-KbUpdate -Name KB4512517` gives me exceptions for unknown function/cmdlet of `Invoke-SqliteQuery`:

![image](https://user-images.githubusercontent.com/6683266/63581136-3d8a1c00-c58e-11e9-923b-6caf73012a66.png)

The results seem to return fine though. Am I suppose to have another module installed?

Again, great work.

**Comment by potatoqualitee** [comment]
Thanks so much for the feedback!

That is an internal function - I am unsure why it's an issue for you. I just tried from my Win10 machine with no issues.

![image](https://user-images.githubusercontent.com/8278033/63590594-91a3f900-c5ac-11e9-8622-1eef167e3ec7.png)

Lemme try on another server and see what's up.

**Comment by potatoqualitee** [comment]
Can you close your session and reopen and try again?

**Comment by potatoqualitee** [comment]
Ah ha, this is from the dependent module, PSSQLite. kbupdate shouldn't be able to load w/o it - it's listed as a dependent module and should auto download/install.

**Comment by sk3pp3r** [comment]
#me2 :-)
I got the same error on my computer.
Windows 10

```
Invoke-SqliteQuery : The term 'Invoke-SqliteQuery' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:122 char:26
+                 $items = Invoke-SqliteQuery -DataSource $db  -Query " ...
+                          ~~~~~~~~~~~~~~~~~~    + CategoryInfo          : ObjectNotFound: (Invoke-SqliteQuery:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

```

**Comment by sk3pp3r** [comment]
solution:

Install module "PSSQLite"
`Install-Module -Name PSSQLite`
[PSSQLite](https://www.powershellgallery.com/packages/PSSQLite/1.0.3)

**Comment by potatoqualitee** [comment]
Thanks @sk3pp3r 

Should have been required on Import 🤔 Are yall importing using psm1? If so, when importing modules with a psd1, that is the formal, better way. You won't expose internal commands and you'll get messages that let you know things like this. So it'd be `Import-Module kbupdate` if the module is in your `$env:psmodulepath`. If not, then `Import-Module C:\temp\kbupdate\kbupdate.psd1`
