### ISSUE TITLE
PowerShell Script Functionality

### ISSUE THREAD

**Issue by maczamora** [potatoqualitee/kbupdate#62]
Hello, trying to understand in the PowerShell script how you are able to select or open up a download dialog box... Not sure if that makes sense. It appears the script may be doing some web scraping with the download dialog button, but not 100% sure. Any information on this would be helpful for better understanding.

**Comment by potatoqualitee** [comment]
Hey @maczamora,
This module obtains the information in one of three ways

Default: local sqlite db
If no matches: scrapes the web
If specified: WSUS API

The approach for scraping the website is that basically, you look at the `<form`, see where it POSTs, then send a payload to that. No "opening" a button is required. If an opening button was required, that would interact with the IE engine, and this module does not interact with the IE engine.

**Comment by maczamora** [comment]
Hi @potatoqualitee , 

Thank you for the information, when webscraping, I can see it does a post for size, updateid, and uidinfo. It looks like I'm able to run those few lines in powershell and see the results with the download link. Now, if I try the same thing with let's say postman, no luck. Results are different. IS there something that PowerShell is doing to see the javascript code that holds the download link?

**Comment by potatoqualitee** [comment]
i have no idea, sorry. you can potentially ask the guy where i got it from:

https://keithga.wordpress.com/2017/05/21/new-tool-get-the-latest-windows-10-cumulative-updates/
