### ISSUE TITLE
Get Latest Update SupersededBy?

### ISSUE THREAD

**Issue by cfreeman21** [potatoqualitee/kbupdate#63]
Great Tool!

I have been given a list of KB's to apply to workstations but the tool used give the original KB that fixes a vulnerability.  That said I was looking for a way without clicking a million times to put the KB in and the latest update stemmed from that.  Here is an example where grabs most but not all SupersededBy.

(Get-KbUpdate -Name KB4011103 -Architecture x86 -Latest).SupersededBy

Output from Powershell:
     Kb Description
     -- -----------
4011636 Security Update for Microsoft Office 2013 (KB4011636) 32-Bit Edition
4011690 Security Update for Microsoft Office 2013 (KB4011690) 32-Bit Edition
4018330 Security Update for Microsoft Office 2013 (KB4018330) 32-Bit Edition
4032239 Security Update for Microsoft Office 2013 (KB4032239) 32-Bit Edition
4461445 Security Update for Microsoft Office 2013 (KB4461445) 32-Bit Edition
4461537 Security Update for Microsoft Office 2013 (KB4461537) 32-Bit Edition
4462138 Security Update for Microsoft Office 2013 (KB4462138) 32-Bit Edition
4464504 Security Update for Microsoft Office 2013 (KB4464504) 32-Bit Edition
4464558 Security Update for Microsoft Office 2013 (KB4464558) 32-Bit Edition

Output from Web:
Security Update for Microsoft Office 2013 (KB4011636) 32-Bit Edition
Security Update for Microsoft Office 2013 (KB4011690) 32-Bit Edition
Security Update for Microsoft Office 2013 (KB4018330) 32-Bit Edition
Security Update for Microsoft Office 2013 (KB4032239) 32-Bit Edition
Security Update for Microsoft Office 2013 (KB4461445) 32-Bit Edition
Security Update for Microsoft Office 2013 (KB4461537) 32-Bit Edition
Security Update for Microsoft Office 2013 (KB4462138) 32-Bit Edition
Security Update for Microsoft Office 2013 (KB4464504) 32-Bit Edition
Security Update for Microsoft Office 2013 (KB4464558) 32-Bit Edition **- Missing from PowerShell output**
Security Update for Microsoft Office 2013 (KB4475607) 32-Bit Edition **- Missing from PowerShell output**

Thoughts?

**Comment by cfreeman21** [comment]
What would your thoughts be to resolve this?

**Comment by potatoqualitee** [comment]
hey @cfreeman21 - sorry for the delayed response. I'm not working on this module at this time and likely won't have an answer for a while. Please feel free to poke through the code. If you can find the issue and the solution is quick, I can potentially fix or will also accept a fix.

**Comment by potatoqualitee** [comment]
Hey @cfreeman21 - figured this out as I was about to go to sleep! The issue is that you'd need to specify Web, otherwise, it just finds the latest from the database which may be outdated.

`(Get-KbUpdate -Name KB4011103 -Architecture x86 -Latest -Source Web).SupersededBy`

I'd love to automate the db and update every day, but haven't gotten around to it yet and likely won't for another couple years :/

**Comment by potatoqualitee** [comment]
![image](https://user-images.githubusercontent.com/8278033/70426687-b6e14800-1a73-11ea-8ea6-f0c04e3630ce.png)
