### ISSUE TITLE
Latest is returning not the last update

### ISSUE THREAD

**Issue by galvanopus** [potatoqualitee/kbupdate#66]
**Command:**
`Get-KbUpdate -Product '.NET Framework 3.5' -Pattern 'Security and Quality Rollup' -OperatingSystem 'Windows Server 2012 R2' -Latest`

**Actual result:**
`2019-05 Security and Quality Rollup for .NET Framework 3.5, 4.5.2, 4.6, 4.6.1, 4.6.2, 4.7, 4.7.1, 4.7.2, 4.8 for Windows 8.1 and Server 2012 R2 for x64 (KB4499408)`

**Expected result:**
`2019-09 Security and Quality Rollup for .NET Framework 3.5 for Windows 8.1 and Server 2012 R2 for x64 (KB4514371)`

Might re related to #63.

**Comment by potatoqualitee** [comment]
Hey @galvanopus - the issue is indeed similar to #63 - the db is out of date :/ So you'd need to specify Web.

`Get-KbUpdate -Product '.NET Framework 3.5' -Pattern 'Security and Quality Rollup' -OperatingSystem 'Windows Server 2012 R2' -Latest -Source Web`

I was working on an automation thing to keep the db up to date but got tired. Perhaps I can just switch the default to Web instead the DB

**Comment by galvanopus** [comment]
I have tried
`Get-KbUpdate -Product '.NET Framework 3.5' -Pattern 'Security and Quality Rollup' -OperatingSystem 'Windows Server 2012 R2' -Latest -Source Web`

There was no result at all. Moreover I have tried
`Get-KbUpdate -Product '.NET Framework 3.5' -Pattern 'Security and Quality Rollup' -OperatingSystem 'Windows Server 2012 R2' -Latest`

and the result was:
```
Invoke-SqliteQuery : Cannot validate argument on parameter 'DataSource'. The argument is null, empty, or an element of the argument collection contains a null value. Supply a collection that does not contain any null values and then try the command again.
At line:122 char:57
+                 $items = Invoke-SqliteQuery -DataSource $db  -Query " ...
+                                                         ~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-SqliteQuery], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Invoke-SqliteQuery

WARNING: [00:12:28][Get-KbItemFromDb] No results found for Security and Quality Rollup
```

**Comment by potatoqualitee** [comment]
damn, k ill give it a look when ive got time, tho it'll be a while sorry

**Comment by potatoqualitee** [comment]
can repro, working on it now

**Comment by potatoqualitee** [comment]
should work now, plz check out latest release
