### ISSUE TITLE
Make a better get-hotfix - like Get-KbInstalledUpdate

### ISSUE THREAD

**Issue by potatoqualitee** [potatoqualitee/kbupdate#67]
````
Get-ChildItem -Path HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall -ErrorAction SilentlyContinue | Get-ItemProperty -ErrorAction SilentlyContinue | Where-Object DisplayName -match KB4498951
````

**Comment by codaamok** [comment]
Hey, just stumbled across this while checking out the repo.

Typically only product updates live in that registry key, e.g. Office (MSI based installs). You won't find OS updates there. 

Maybe it's worth sharing, in case you didn't already know, system updates live in the Win32_QuickFixEngineering class which is what `Get-HotFix` uses. Not all system updates live there though, I have a feeling .NET updates don't show up which is effectively core to Windows 10 now - could be wrong, 90% sure.

**Comment by potatoqualitee** [comment]
Thanks so much @codaamok ! I've completed the command and it's currently in a pull request. Let me know what you think. I do use Win32_QuickfixEngineering

https://github.com/potatoqualitee/kbupdate/blob/9aefb335f440c2435566fa145a160b7eb29c8135/public/Get-KbInstalledUpdate.ps1

![image](https://user-images.githubusercontent.com/8278033/73307263-270f7d00-421e-11ea-8323-bc90d5b3239c.png)

**Comment by codaamok** [comment]
Ja, looks good. Sorry if stupid question, but where in that are you looking in the registry? Is that `Get-Package` is doing? I didn't even know what Package Management was in PoSH 5+ until now!

I really hate QFE though because (and I don't know why) the dates returned for InstalledOn are _always_ in en-us format. I found this once online and have it in my profile:

`Get-HotFix | Select-Object description,hotfixid,installedby,@{l="InstalledOn";e={[DateTime]::Parse($_.psbase.properties["installedon"].value,$([System.Globalization.CultureInfo]::GetCultureInfo("en-US")))}}`

Also, in the script block, your comment suggests you struggle to preserve parameter as array. Prefix the parameter data type as `[String[]]` then it's preserved, no need for the hashtable hot potato then :-)

![image](https://user-images.githubusercontent.com/6683266/73353856-4218d600-428c-11ea-92b0-d364860d4a26.png)

**Comment by codaamok** [comment]
I should elaborate on that date format bit: if you're on a system that isn't regionlised as en-us the InstalledOn property will be returned blank.

**Comment by codaamok** [comment]
Also, @indented-automation helped me understand in the WinAdmins Discord that it's positional binding that's going on here as `-ArgumentList` accepts an array. The array isn't being flattened to a string, it's just passing all the elements in the array as individual parameters to the script block.

While the script block here only has 1 parameter, what I suggested previously will still work. But if one day you ever want to pass an array to a script block, while passing other arguments, I guess we could:

```
Invoke-Command -ScriptBlock $scriptblock -ArgumentList @(@("Item1","Item2"),$someothervar)
```

This binds the first argument, which is the array, and the second argument which is whatever `$someothervar` is.

Another method to pass an array as the sole argument to the script block with 1 parameter is:

```
Invoke-Command -ScriptBlock $scriptblock -ArgumentList (,@("Item1","Item2"))
```

**Comment by potatoqualitee** [comment]
Thank you so much for the detailed review, @codaamok! Sorry I didn't notice this earlier. I released the final and will re approach with your comments in mind.

Here's the final. Basically, I scoured the internet to find any instance of how people discover patches and saw which ones provided information that the others didn't. So the registry does have extra information that Get-Package does not.

https://github.com/potatoqualitee/kbupdate/blob/master/public/Get-KbInstalledUpdate.ps1

I also didn't know much about Get-Package either! Same for Get-WindowsPackage. Too bad it's not a complete solution, tho. Get-Pakage | Uninstall-Package totally didnt ever work for me.

**Comment by potatoqualitee** [comment]
If I add this `[DateTime]::Parse($_.psbase.properties["installedon"].value,$([System.Globalization.CultureInfo]::GetCultureInfo("en-US"))` to my script, will it still work on your machine?

**Comment by potatoqualitee** [comment]
Ohh that makes total sense with the ArgumentList, thank you. I really thought it'd keep the array to itself but can see how it wouldnt. That's cool. thanks, fixed!

**Comment by potatoqualitee** [comment]
closing but would still like to know if i can fix that installedon value for you
