### ISSUE TITLE
Not working on Linux 

### ISSUE THREAD

**Issue by yogeshkathayat** [potatoqualitee/kbupdate#96]
First of all thanks for this awesome module :)

I tried running it on my Linux machine It's not working.

**Ubuntu 18.04.4
PowerShell 6.2.4**

STEPS:-

1. Installation
`Install-Module kbupdate`
Installation completed without any error
2.  when I run **Get-KbUpdate -Name KB405711** command it's throwing following error.
```
Get-KbUpdate -Name KB4057119 
 Get-KbUpdate : The 'Get-KbUpdate' command was found in the module 'kbupdate', but the module could not be loaded. For more information, run 'Import-Module kbupdate'.
```
3. Then I tried to run **Import-Module kbupdate** which throws the following error.
```
Import-Module : Cannot find drive. A drive with the name 'HKLM' does not exist.
At line:1 char:1
+ Import-Module kbupdate
```

**Comment by potatoqualitee** [comment]
thanks for the issue, @yogeshkathayat ! I justttt added back support for Linux. I'll publish now and you can try again. BRB

**Comment by potatoqualitee** [comment]
k try now

**Comment by yogeshkathayat** [comment]
It's working now. Thanks
