### ISSUE TITLE
Save-KbUpdate and Install-KbUpdate not working with -FilePath

### ISSUE THREAD

**Issue by GabrielDzsurdzsa** [potatoqualitee/kbupdate#97]
I have built an automations solution using PSWindowsUpdate Powershell library and KBUpdate. 

Using PSWindowsUpdate, I procure the list of available updates with KB #s. 

Then I use Save-KBUpdate to save the installers in a local folder. 

Finally, I use Install-KBUpdate with -FilePath, and also tried the call without the -HotFixId and with it.

The errors I am getting when running Install-KBUpdate are: 

"Could not determine KB from C:\users\gabriel\desktop\visual studio code solutions\bit automations framework\libraries\lib-exe\bitafw10d\Resources\Microsoft 
Updates\KB4481252\silverlight_x64_16cfdfe075ee9249845eccff913acc4386a0a1e6.exe. Looked for '-kbnumber-'. Please provide a HotfixId"

and

"Failure on GABRIEL-LAP | The client cannot connect to the destination specified in the request. Verify that the service on the destination is running and is accepting requests. 
Consult the logs and documentation for the WS-Management service running on the destination, most commonly IIS or WinRM. If the destination is the WinRM service, run the following command on the destination to analyze and configure the WinRM service: "winrm quickconfig".

Any idea why I can't install the updates from the KB installer files themselves?

**Comment by GabrielDzsurdzsa** [comment]
Here is my interface code. I have built a menu in my solutions framework which displays available updates using PSWindowsUpdate, allows the user to select one or more updates from the numbered items menu to download into a local Resources folder, by KB subfolders, and supposedly install the update from these files:

`    #loop through individual selections and download selected updates from menu
    foreach ($kb in ([string]$KBS).Replace(" ", "").Split(",")) {
        foreach ($menuItem in $updatesMenu) {
            if ($kb -eq $menuItem.No) {        
                #first, check if kb is installed before downloading
                $isInstalled =  Get-KbInstalledUpdate -Pattern $menuItem.KB
                if(!$isInstalled) {
                    ("Downloading $($menuItem.KB) - $($menuItem.UpdateTitle)...") *>> $logFile
                    #x64 bit updates only
                    (New-Item -Path "$root\Resources\Microsoft Updates\$($menuItem.KB)" -ItemType Directory -Force -Verbose) *>> $logFile
                    (Save-KbUpdate -Name $menuItem.KB -Architecture x64 -Path "$root\Resources\Microsoft Updates\$($menuItem.KB)") *>> $logFile
                    $res = Get-ChildItem -Path "$root\Resources\Microsoft Updates\$($menuItem.KB)" | Select-Object Directory, Name
                    foreach($resource in $res) {
                        #install update from downloaded KB file
                        (Install-KbUpdate -FilePath "$($resource.Directory)\$($resource.Name)" -HotfixId $menuItem.KB) *>> $logFile
                    }
                }                          
            }
        }
    }`

**Comment by GabrielDzsurdzsa** [comment]
Calling WinRM quickconfig seems to have solved it. 

Now I'm getting a different error: 

[13:07:35][Install-KbUpdate] Failure on GABRIEL-LAP | Cannot invoke the Invoke-DscResource cmdlet. The Invoke-DscResource cmdlet is in progress and must return before Invoke-DscResource can be invoked. Use -Force option if that is
available to cancel the current operation.

-Force is not supported on Install-KBUpdate

**Comment by GabrielDzsurdzsa** [comment]
They seem to work now. I believe the last error I was receiving was due to a previous successful update which required restart. The output of which I must have not seen in my log.

**Comment by potatoqualitee** [comment]
For anyone else who comes here:  The Invoke-DscResource cmdlet is in progress and must return before Invoke-DscResource can be invoked. Use -Force option if that is available to cancel the current operation." Unfortunately, I could not find a resolution other than to restart the server and rename the corrupted file it was repeatedly attempting to install. This appears to have cancelled the process, though a clean, repeatable resolution would have been preferred.
