### ISSUE TITLE
Microsoft Catalog bug

### ISSUE THREAD

**Issue by audriusurbo** [potatoqualitee/kbupdate#98]
Hi, 
I am using get-kbupdate -pattern "$kb $version" | save-kbupdate in a loop. I am getting KBs from Microsoft Catalog. The site sometimes spits out all updates including random drivers and save-kbupdate downloads them. Is there a way to check the files the get-update before saving them? 
![image](https://user-images.githubusercontent.com/61513952/75369732-e574ff00-58bb-11ea-8d96-3a5e15889d12.png)

**Comment by audriusurbo** [comment]
Start-Sleep -Seconds 5
before get-kbupdate improved the rate it returns correct kbupdate and not random geforce drivers

**Comment by potatoqualitee** [comment]
Interesting! My results were different too. I'd try `Get-KbUpdate -Pattern "$kb $version" | Where Title -match 1809 | Save-KbUpdate` ...

**Comment by audriusurbo** [comment]
Hi, Thanks for the prompt response.

I will try adding Where element. I think it would not find it and it wont download that KB update. The reason I am downloading without architecture parameter is because Microsoft does not always put the correct architecture in the update details (e.g. x64 update details: ARM64 AMD64 x86) only filename indicates 100% if it's x64 or x86, so I download all of them and sort them out later. But since this microsoft catalog bug returns garbage, it tries to download everything. Tried to reproduce in my browser, but it seems to be random. If you search for update which is not cached somewhere it has a higher chance to return garbage.

Ideally if first result does not match the $pattern it should try again.

**Comment by potatoqualitee** [comment]
Unfortunately, there's not much we can do for all the different ways a bad source can be bad. For now, I'll leave this to the `Where` clause and hope that the catalog starts returning better results more consistently.
